### ISSUE TITLE
Validate the configuration and fail-fast

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#222]
e.g. required fields for deploy vs provision, sane values for CPU, memory

**Comment by philipstaffordwood** [comment]
**Note:** `kubeadm` startup fails on primary master fails with 1 VM.

**Comment by philipstaffordwood** [comment]
Taking an approach like:

[```
		if err := p.ValidateKindCluster(); err != nil {
			return fmt.Errorf("Failed to validate cluster configuration, %s", err)```](https://github.com/philipstaffordwood/platform-cli/blob/675755a59a045009bcceccbe950d0824bd9f03f7/cmd/provision.go#L44-L45)

[```
// ValidateKindCluster is to validate a platform config
func (c *Platform) ValidateKindCluster() error {


	if c.CA == nil {
		return fmt.Errorf(NoCaSection)
	}
	if c.IngressCA == nil {
		return fmt.Errorf(NoIngressCaSection)
	}
	if _, err := c.GetCA(); err != nil {
		return errors.Wrap(err, InvalidCA)
	}


	return nil
}```](https://github.com/philipstaffordwood/platform-cli/blob/675755a59a045009bcceccbe950d0824bd9f03f7/pkg/platform/platform.go#L690-L704)
