### ISSUE TITLE
Rolling Update - When choosing which node to promote as new etcd leader, use the newest member

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#400]
To prevent the etcd leader moving to a node that is still going to be rolled.

**Comment by philipstaffordwood** [comment]
Capped at <kbd>S</kbd>

**Comment by philipstaffordwood** [comment]
Currently the existing sorting is not working on lab environment (possible misconfiguration?) see https://github.com/flanksource/karina/issues/430
