### ISSUE TITLE
Kube Web/Resource View - Read cluster name

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#433]
See https://github.com/flanksource/canary-checker/blob/master/pkg/kube.go#L46

**Comment by philipstaffordwood** [comment]
If using a kubeconfig file for connectivity the name is taken from that.

For in-cluster service-accounts:
* **kube-resource-report** allows specifying the name via the `DEFAULT_CLUSTER_NAME` environment variable
* **kube-web-view** has it [hardcoded](https://github.com/hjacobs/kube-web-view/blob/f30c148f32a29f5af23238406ff1a3c46dd21ee5/kube_web/cluster_discovery.py#L72) as `local`

Simplest approach for both seems to just to always generate the kubeconfig file.
Looking at recent deployments the SA approach is giving access issues anyway.
