### ISSUE TITLE
Default template for PR

### ISSUE THREAD

**Issue by tobernguyen** [flanksource/karina#668]
Should we create a default template for PR so we can encourage higher quality PR?

**Comment by moshloop** [comment]
Sure - We probably also need some merge blocking linting for commit messages

**Comment by tobernguyen** [comment]
> Sure - We probably also need some merge blocking linting for commit messages

Conventional commits might be a good start? https://www.conventionalcommits.org/en/v1.0.0/
With conventional commits, we can easily use `semantic-release` to automate the release process in the future.
