### ISSUE TITLE
Implement conventional commits

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#673]
* Add a new CI job to lint git commits
* Add a new manual CI job to create new releases with a changelog

**Comment by tobernguyen** [comment]
I'm been using Probot for a while and it's been the best solution: https://github.com/zeke/semantic-pull-requests. But since it is an app, it needs to be installed on GitHub repositories we want to enable. I have requested to install it to Karina. If you insist on using GitHub actions instead of an app, I can dig into GitHub actions instead.

**Comment by tobernguyen** [comment]
@moshloop can you point me to where I can find how we are creating a new release currently? And do you want to automate the generation of a commit to update the `CHANGELOG.md` at the root or just the body of the release on GitHub?

**Comment by tobernguyen** [comment]
> @moshloop can you point me to where I can find how we are creating a new release currently? And do you want to automate the generation of a commit to update the `CHANGELOG.md` at the root or just the body of the release on GitHub?

Disregard the question about how we are creating a new release. I think I found it: https://github.com/flanksource/karina/blob/master/.github/workflows/binary.yml. So I guess you are creating a tag manually then this workflow will be kicked off to create binaries then create a new github release then upload the binaries to the created release, right?

The question about CHANGELOG is still there, BTW.

**Comment by tobernguyen** [comment]
> > @moshloop can you point me to where I can find how we are creating a new release currently? And do you want to automate the generation of a commit to update the `CHANGELOG.md` at the root or just the body of the release on GitHub?
> 
> Disregard the question about how we are creating a new release. I think I found it: https://github.com/flanksource/karina/blob/master/.github/workflows/binary.yml. So I guess you are creating a tag manually then this workflow will be kicked off to create binaries then create a new github release then upload the binaries to the created release, right?
> 
> The question about CHANGELOG is still there, BTW.

Per discussion from Slack, we want to automate the changelog on the github release level only, no updating CHANGELOG.md.

**Comment by Aamir-raza-1** [comment]
@tobernguyen 
Regarding the discussion to release with changelog I just created github workflow
https://github.com/flanksource/kommons/pull/16

@moshloop So after its approval,I suggest to use this action.
Source:
https://github.com/fregante/release-with-changelog

**Comment by tobernguyen** [comment]
> @tobernguyen
> Regarding the discussion to release with changelog I just created github workflow
> [flanksource/kommons#16](https://github.com/flanksource/kommons/pull/16)
> 
> @moshloop So after its approval,I suggest to use this action.
> Source:
> https://github.com/fregante/release-with-changelog

Oh. I'm working on this already to leverage semantic-release to automatically determine the next release version -> create tag -> create release with changelog derived from commits.
