### ISSUE TITLE
Lint job is flakey

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#677]
Might make sense to move away from the imported action and/or upgrade it.

**Comment by tobernguyen** [comment]
In which run it is flaky? Do you have a link(s) to a flakey run?

**Comment by moshloop** [comment]
https://github.com/flanksource/karina/actions/runs/553683716

**Comment by tobernguyen** [comment]
> https://github.com/flanksource/karina/actions/runs/553683716

Yeah this failed run is because in this PR https://github.com/flanksource/karina/pull/674 we added `docs/mkdocs.yml` but didn't add it to ignore list. I fixed this in my PR https://github.com/flanksource/karina/pull/676. It should work again now.

**Comment by moshloop** [comment]
Fixed the reporting of linting errors in #681
