### ISSUE TITLE
Rename platform-cli to karina

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#77]
platform-cli is a bit too generic we need something a little more memorable and shorter to say

Please create new suggestions and/or vote for current suggestions

**Comment by moshloop** [comment]
platformadm or platformctl

**Comment by moshloop** [comment]
phoenix

**Comment by moshloop** [comment]
podium

**Comment by moshloop** [comment]
patron - spannish for skipper

**Comment by moshloop** [comment]
armada

**Comment by moshloop** [comment]
marlin (or another fish name)

**Comment by superolo92** [comment]
** k** ~~ubernetes~~ + ~~s~~** ailor**  -> kailor( tool related to the operation and maintenance of kubernetes)

**Comment by K-DOT** [comment]
I like Kailor

**Comment by sainivikas** [comment]
kare  
(Kubernetes + care)       (tool for K8 administration/operation/maintenance)

**Comment by mazzy89** [comment]
I like Kailor too.

**Comment by mazzy89** [comment]
kozyain - from the russian master

**Comment by moshloop** [comment]
What about [helios](https://en.wikipedia.org/wiki/Helios_(spacecraft)) the spacecraft(s) that have the records for being the fastest and until recently the closest flyby to the sun. Also ties in nicely with our t-shirt design: 
![t-shirt](https://user-images.githubusercontent.com/1489660/74809501-f8089a80-52f5-11ea-8f1d-75c0c4bb76c1.jpeg)

**Comment by teodor-pripoae** [comment]
Helios name conflicts with spotify/helios which is also in the container orchestration zone.

**Comment by moshloop** [comment]
How about Karina as in the [constellaton](https://en.wikipedia.org/wiki/Carina_(constellation)) meaning the Keel of a ship?

The CLI could then be called `kar` or `karctl` or `karadm`

**Comment by K-DOT** [comment]
I like Karina

**Comment by mazzy89** [comment]
I like it too. Pretty common female name in Russia though 😜
